name: NPM Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.1

      - name: install and build
        run: |
          npm install
          npm run build

  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: JS-DevTools/npm-publish@v1
        with:
          registry: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}